### PR TITLE
Fix PostgreSQL installation error and so also system-test-postgresql in Drone and update to 4.0-dev

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue [https://github.com/joomla/joomla-cms/pull/28462](https://github.com/joomla/joomla-cms/pull/28462).

### Summary of Changes

See title and the changes.

### CODE REVIEW

**Comment by richard67** [comment]
I've adapted the update sql script to latest components and modules, as they are in your joomla.sql files (which are ok). What remains to be done is the same for the plugins. Will do later. Stay tuned and wait with merging this, or merge and I will make a new PR then.

**Comment by Quy** [comment]
Thank you! There is an unrelated commit in administrator/templates/atum/scss/template-rtl.scss.

**Comment by richard67** [comment]
Yes, that comes from merging up latest changes from 4.0-dev so you are up to date with the base branch. Let me commit one SQL code style thing forst, then I check.

**Comment by richard67** [comment]
@Quy Seems you were right, no idea how that came in. Just reverted it now, you can merge.

**Comment by Quy** [comment]
You are the best. Thanks again!

**Comment by richard67** [comment]
What remains to be done is to check and if necessary update the list of core extensions in section "Now protect from disabling essential core extensions" at the bottom of the update sql. These values for `protected` and `enabled` should be the same as in joomla.sql I think.

**Pull request merged**
